[package]
name = "stylus-erc20"
version = "0.1.0"
edition = "2021"  

[dependencies]
stylus-sdk = "0.5.0"

alloc = { version = "0.1.0", package = "rustc-std-workspace-alloc" }

[lib]
crate-type = ["cdylib"]

[features]
default = []


